# Generated by Django 4.2.7 on 2026-02-17 12:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_bookingpreview_booking_commission_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='finance_own_owner_i_171ac4_idx'), models.Index(fields=['period_start', 'period_end'], name='finance_own_period__765369_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('account', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('slot_revenue', 'Slot Revenue'), ('gst_collected', 'GST Collected'), ('platform_fee_revenue', 'Platform Fee Revenue'), ('gst_on_platform_fee', 'GST on Platform Fee'), ('commission_revenue', 'Commission Revenue'), ('owner_payable', 'Owner Payable')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='bookings.booking')),
            ],
            options={
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'entry_type'], name='finance_led_booking_cecec5_idx'), models.Index(fields=['account', 'created_at'], name='finance_led_account_0feb0e_idx')],
            },
        ),
    ]
