# Generated by Django 4.2.7 on 2026-02-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfowner',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
