# Generated by Django 4.2.7 on 2026-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_turfowner_account_holder_name_turfowner_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='used_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
