# Generated by Django 4.2.7 on 2026-02-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_promocode_customuser_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualified_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_cashback_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_install_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.turfowner'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='qr_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='qr_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='qr_installs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='qr_scans',
            field=models.IntegerField(default=0),
        ),
    ]
