# Generated by Django 4.2.7 on 2026-02-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_qualified_referrals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_booking_completed',
            field=models.BooleanField(default=False),
        ),
    ]
