# Generated by Django 4.2.7 on 2026-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_coupon_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging device token', null=True),
        ),
    ]
