# Generated by Django 4.2.7 on 2026-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_fcm_token_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='purpose',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('reset', 'Password Reset')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone', 'purpose', 'is_verified'], name='users_otpre_phone_cfb555_idx'),
        ),
    ]
