# Generated by Django 4.2.7 on 2026-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_otprequest_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otprequest',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice Call')], default='sms', max_length=5),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='purpose',
            field=models.CharField(blank=True, choices=[('registration', 'Registration'), ('reset', 'Password Reset'), ('login', 'Login'), ('phone_change', 'Phone Change')], default='', max_length=20),
        ),
    ]
