# Generated by Django 4.2.7 on 2026-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_otp_method_and_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday_credited_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_booking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_booking_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loyalty_tier',
            field=models.CharField(default='newbie', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
