# Generated by Django 4.2.7 on 2026-03-04 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0012_bookingpreview_first_booking_discount'),
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('first_booking', 'First Booking Discount'), ('referral', 'Referral Program'), ('last_minute', 'Last Minute Deals'), ('streak', 'Streak Rewards'), ('loyalty', 'Loyalty Tiers'), ('captain', 'Captain Rewards'), ('wallet', 'Wallet Cashback')], db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('expiry_days', models.IntegerField(default=30)),
                ('streak_thresholds', models.JSONField(blank=True, default=list)),
                ('streak_rewards', models.JSONField(blank=True, default=list)),
                ('loyalty_tiers', models.JSONField(blank=True, default=list)),
                ('loyalty_perks', models.JSONField(blank=True, default=list)),
                ('referral_rewards', models.JSONField(blank=True, default=dict)),
                ('last_minute_windows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Config',
                'verbose_name_plural': 'Offer Configs',
                'ordering': ['offer_type'],
            },
        ),
        migrations.CreateModel(
            name='OfferUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(db_index=True, max_length=50)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_usages', to='bookings.booking')),
                ('offer_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='growth.offerconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Usage',
                'verbose_name_plural': 'Offer Usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer_type', 'created_at'], name='growth_offe_offer_t_2e2f25_idx'), models.Index(fields=['user', 'offer_type'], name='growth_offe_user_id_b9f365_idx')],
            },
        ),
    ]
