# Generated by Django 4.2.7 on 2026-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truff_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('promo', 'Promo Code'), ('offer', 'Special Offer'), ('announcement', 'Announcement'), ('booking', 'Booking Reminder'), ('test', 'Test')], default='announcement', max_length=50)),
                ('target_type', models.CharField(choices=[('all', 'All Users'), ('owners', 'Turf Owners'), ('customers', 'Customers'), ('recent_bookers', 'Recent Bookers (last 30 days)'), ('inactive', 'Inactive Users (>30 days)'), ('token', 'Single Device (by token)')], default='all', max_length=20)),
                ('device_token', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, help_text='e.g. home, offers, booking', max_length=100)),
                ('promo_code', models.CharField(blank=True, max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
