# Generated by Django 4.2.7 on 2026-02-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0006_slotmaster_blockedslot_slotoffer_and_more'),
        ('bookings', '0004_bookingpreview_booking_commission_booking_gst_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to='bookings.booking')),
                ('slot_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to='turfs.slotmaster')),
            ],
            options={
                'indexes': [models.Index(fields=['slot_master', 'booking_date'], name='bookings_bo_slot_ma_6ad7de_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=models.UniqueConstraint(fields=('slot_master', 'booking_date'), name='unique_slot_per_date'),
        ),
    ]
