# Generated by Django 4.2.7 on 2026-02-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bulletproof_slot_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='credits_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
