# Generated by Django 4.2.7 on 2026-02-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0006_booking_credits_used_booking_is_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.CharField(blank=True, help_text='Provider conference ID (Twilio/Exotel/etc.)', max_length=100, null=True, unique=True)),
                ('owner_called', models.BooleanField(default=False)),
                ('customer_called', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('connected', 'Connected'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='bookings.booking')),
                ('initiated_by', models.ForeignKey(help_text='The turf owner who clicked Call Customer', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['booking', '-started_at'], name='bookings_ca_booking_cbec5a_idx'), models.Index(fields=['initiated_by', '-started_at'], name='bookings_ca_initiat_32fb1b_idx'), models.Index(fields=['status'], name='bookings_ca_status_4e1f57_idx')],
            },
        ),
    ]
