# Generated by Django 4.2.7 on 2026-02-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_add_callrecord_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='admin_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='admin_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
