# Generated by Django 4.2.7 on 2026-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_first_booking',
            field=models.BooleanField(default=False),
        ),
    ]
