# Generated by Django 4.2.7 on 2026-02-28 05:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_is_first_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpreview',
            name='first_booking_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
