# Generated by Django 4.2.7 on 2026-03-06 17:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_otprequest_purpose'),
        ('bookings', '0012_bookingpreview_first_booking_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.promocode'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coupon discount amount applied to this booking', max_digits=10),
        ),
    ]
