# Generated by Django 4.2.7 on 2026-02-09 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turf',
            name='sports',
            field=models.ManyToManyField(related_name='turfs', to='turfs.sport'),
        ),
        migrations.AddField(
            model_name='review',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['status', 'is_active'], name='turfs_turf_status_cc5939_idx'),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['latitude', 'longitude'], name='turfs_turf_latitud_feec0c_idx'),
        ),
        migrations.AddIndex(
            model_name='turf',
            index=models.Index(fields=['owner', 'status'], name='turfs_turf_owner_i_a3ae14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('turf', 'user')},
        ),
    ]
