# Generated by Django 4.2.7 on 2026-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
