# Generated by Django 4.2.7 on 2026-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_turf_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
