# Generated by Django 4.2.7 on 2026-02-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_alter_turf_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
