# Generated by Django 4.2.7 on 2026-02-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_alter_turf_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_masters', to='turfs.turf')),
            ],
            options={
                'ordering': ['turf', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='turfs.slotmaster')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='turfs.turf')),
            ],
            options={
                'ordering': ['date', 'slot_master__start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlotOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20.00 for 20%) or flat amount (e.g. 100.00 for ₹100 off)', max_digits=10)),
                ('max_discount_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount ceiling for percentage offers. Ignored for flat offers.', max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='turfs.slotmaster')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slot_master', 'is_active', 'valid_from', 'valid_until'], name='turfs_sloto_slot_ma_2dc1af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='slotmaster',
            index=models.Index(fields=['turf', 'day_of_week', 'is_active'], name='turfs_slotm_turf_id_ded1c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slotmaster',
            unique_together={('turf', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='blockedslot',
            unique_together={('slot_master', 'date')},
        ),
    ]
