# Generated by Django 4.2.7 on 2026-02-19 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfs', '0006_slotmaster_blockedslot_slotoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_turfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turf',
            name='suspend_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
