# Generated by Django 4.2.7 on 2026-02-19 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfs', '0007_turf_approved_by_suspend_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmaster',
            name='disable_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotmaster',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slotmaster',
            name='disabled_mode',
            field=models.CharField(choices=[('none', 'None'), ('temporary', 'Temporary'), ('permanent', 'Permanent')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='slotmaster',
            name='disabled_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='slotmaster',
            index=models.Index(fields=['disabled_mode', 'disabled_until'], name='turfs_slotm_disable_58eaa5_idx'),
        ),
    ]
