# Generated by Django 4.2.7 on 2026-02-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0008_add_slot_disable_modes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='slotmaster',
            name='turfs_slotm_disable_58eaa5_idx',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='disable_reason',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='disabled_mode',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='disabled_until',
        ),
    ]
