# Generated by Django 4.2.7 on 2026-03-03 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfs', '0009_remove_slot_disable_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(help_text='Dict of {field: {old: ..., new: ...}} for changed fields only')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_edits', to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='turfs.turf')),
            ],
            options={
                'verbose_name': 'Turf Edit History',
                'verbose_name_plural': 'Turf Edit Histories',
                'ordering': ['-edited_at'],
            },
        ),
    ]
