# Generated by Django 4.2.7 on 2026-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0010_turf_edit_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfimage',
            name='crop_height',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='turfimage',
            name='crop_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='turfimage',
            name='crop_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='turfimage',
            name='crop_y',
            field=models.FloatField(default=0.0),
        ),
    ]
