# Generated by Django 4.2.7 on 2026-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0011_add_crop_fields_to_turfimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_shutdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf',
            name='shutdown_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='shutdown_notified_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf',
            name='shutdown_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='shutdown_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
